apiVersion: v1
kind: Service
metadata:
  name: cdo-fe-app
  namespace: cdo-fe
  labels:
    app: cdo-fe-app
spec:
  selector:
    app: cdo-fe-app
  ports:
    - name: http
      port: 80
      targetPort: http
