apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Kustomize gom các manifest của backend thành một desired state để ArgoCD apply.
resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- service-monitor.yaml
- prometheus-rule.yaml

# GitHub Actions sẽ cập nhật image tag sau mỗi lần merge vào main.
images:
  - name: cdo-be-app
    newName: ghcr.io/2hm1901/cdo-be-app
    newTag: ae64a1ec3aee7fdfa504371f8186287673c42e45
