apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Kustomize gom các manifest của app thành một desired state để ArgoCD apply.
resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- service-monitor.yaml
- prometheus-rule.yaml

# GitHub Actions sẽ cập nhật image tag sau mỗi lần merge vào main.
images:
- name: cdo-demo-app
  newName: ghcr.io/2hm1901/cdo-demo-app
  newTag: 1e779e7193fdbfdb41c7754052ee6f1f25deafb7
